binance.coin:
   collateral:
      - DEFAULT: USDC
      - LUNC: USDC
      - BUSD: USDC
      - BETH: ETH
   
crypto-com.coin:
   alias-for-name:
      - LUNA: LUNA2
   collateral:
      - DEFAULT: USDT
      - LUNA2: USDC
      - LUNC: USDC
      - BUSD: USDT

timezone.default: Europe/Rome

burningwave.core.static-component-container:
   background-executor.all-tasks-monitoring.enabled: false
   banner.hide: false
   managed-logger.repository: 'org.burningwave.core.SLF4JManagedLoggerRepository'
   modules.export-all-to-all: false
   thread-supplier.max-detached-thread-count: 8
   thread-supplier.max-detached-thread-count.increasing-step: 4
   thread-supplier.max-poolable-thread-count: 0

service:
   mail:
      indicator.notifier:
         text.table.on-top-fixed-header: false
         min-number-of-indicators-detected: 4
         resend-already-notified: true
         show-only-consistent-data: true
         recipient:
            - roberto.gentili.1980@gmail.com
            - fercoletti@gmail.comm