name: RSI detector


on:
  schedule:
#    - cron: "25,55 * * * *"
#    - cron: "25 * * * *"
#    - cron: "25,55 0,1,23 * * *"

#on:
#  push:
#    branches:
#      - main
#    paths:
#      - "**.java"
#      - "**.xml"
#      - "**.xlsx"
#      - ".github/workflows/**"


jobs:


  launch-update:
    name: Launch update
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [18]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update and push report
        run: |
          export GPG_TTY=$(tty)
          echo "${{ secrets.gpg_private_key }}" | gpg --batch --import
          git config user.name "Roberto Gentili"
          git config user.email "roberto.gentili.1980@gmail.com"
          mvn clean dependency:list install
          java -DcryptoComApiKey=${{ secrets.crypto_com_api_key }} -DcryptoComApiSecret=${{ secrets.crypto_com_api_secret }} -DbinanceApiKey=${{ secrets.binance_api_key }} -DbinanceApiSecret=${{ secrets.binance_api_secret }} -DemailAccount=${{ secrets.email_account }} -DemailPassword=${{ secrets.email_password }} -jar ./target/runner-1.0.0.jar org.rg.service.Runner
